### ISSUE TITLE
Will there be a dump containing forum contents?

### ISSUE THREAD

**Issue by p0xus** [Hexorg/CheatEngineTables#2]

**Comment by werirdhat** [comment]
https://www.file-upload.net/download-12344621/Attachments.zip.html

this file contains the post contents.

also, files not mentioned in this list are likely private so might not be good to upload those

**Comment by p0xus** [comment]
Thanks

**Comment by Hexorg** [comment]
I don't think we'll maintain the forum dump as were are trying to become a supportive community on our own.
