### ISSUE TITLE
Please don't remove CTs with cameras/timestops

### ISSUE THREAD

**Issue by FransBouma** [Hexorg/CheatEngineTables#6]
Hi,

great idea to keep the CTs here in a repo, to preserve them for later usage! :) One question: I don't see my 2 CTs for Assassin's Creed Unity/Syndicate which could be they're removed (They added timestop) as they don't contain 'cheats', but they do are valuable for screenshotters, so could you please also keep the CTs which solely hack the camera / timestop? Thanks a lot!

Keep up the good work :)

**Comment by Hexorg** [comment]
We definitely plan to keep camera / timestop tables. 

There are still some Assassin's Creed tables that haven't been moved to a proper folder yet. 

Some tables, however, are named in such a way that it is hard to determine the name of the game they were made for. I will be moving them to /vault if we can't find their target game.

If you can't find your tables in neither /tables nor /vault, feel free to submit them as a merge request here or on /r/cheatengine.
